import React from "react";

const moneyish = (value) => {
  if (value == null) return "";
  if (typeof value === "number") return value.toLocaleString();
  return String(value);
};

export function PrintableReport({ report }) {
  const r = report || {};
  const columns = Array.isArray(r.columns) ? r.columns : [];
  const rows = Array.isArray(r.rows) ? r.rows : [];
  const totals = Array.isArray(r.totals) ? r.totals : [];
  const filters = Array.isArray(r.filters) ? r.filters : [];
  const generatedAt = r.generatedAt ? new Date(r.generatedAt) : new Date();

  return (
    <article className={"print-report " + (r.orientation === "landscape" ? "print-landscape" : "print-portrait")}>
      <header className="print-header">
        <div className="print-brand">
          {r.logoUrl ? <img src={r.logoUrl} alt="" className="print-logo" /> : <div className="print-logo-mark">VP</div>}
          <div>
            <h1>{r.companyName || "VISIONPOS"}</h1>
            {r.companyDetails && <p>{r.companyDetails}</p>}
          </div>
        </div>
        <div className="print-meta">
          <strong>{r.title || "Report"}</strong>
          <span>{r.branchName || "All branches"}</span>
          <span>{generatedAt.toLocaleString()}</span>
        </div>
      </header>

      <section className="print-title-block">
        <h2>{r.reportName || r.title || "Report"}</h2>
        <div className="print-facts">
          <span><b>Generated by:</b> {r.generatedBy || "VISIONPOS"}</span>
          <span><b>Branch:</b> {r.branchName || "All branches"}</span>
          <span><b>Date range:</b> {r.dateRange || "All time"}</span>
        </div>
      </section>

      {filters.length > 0 && (
        <section className="print-filters">
          {filters.map((f) => <span key={f.label}><b>{f.label}:</b> {f.value}</span>)}
        </section>
      )}

      <table className="print-table">
        <thead>
          <tr>{columns.map((c) => <th key={c.key || c.label} className={c.align === "right" ? "num" : ""}>{c.label}</th>)}</tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr><td colSpan={Math.max(columns.length, 1)} className="print-empty">No data for this report.</td></tr>
          ) : rows.map((row, idx) => (
            <tr key={row.id || idx}>
              {columns.map((c) => <td key={c.key || c.label} className={c.align === "right" ? "num" : ""}>{moneyish(row[c.key])}</td>)}
            </tr>
          ))}
        </tbody>
      </table>

      {totals.length > 0 && (
        <section className="print-totals">
          {totals.map((t) => <div key={t.label}><span>{t.label}</span><strong>{t.value}</strong></div>)}
        </section>
      )}

      <footer className="print-footer">
        <span>{r.footer || "Generated by VISIONPOS"}</span>
        <span className="page-number" />
      </footer>
    </article>
  );
}

export const PrintableDailySales = ({ report }) => <PrintableReport report={{ ...report, reportName: report?.reportName || "Daily Sales Report" }} />;
export const PrintableInventory = ({ report }) => <PrintableReport report={{ ...report, reportName: report?.reportName || "Inventory Report" }} />;
export const PrintableCustomerStatement = ({ report }) => <PrintableReport report={{ ...report, reportName: report?.reportName || "Customer Statement" }} />;
export const PrintableProfit = ({ report }) => <PrintableReport report={{ ...report, reportName: report?.reportName || "Profit Report" }} />;

export function buildReportDocument({ title, companyName, companyDetails, logoUrl, branchName, generatedBy, dateRange, filters, headers, rows, totals, orientation }) {
  const columns = headers.map((label, index) => {
    const key = "c" + index;
    const align = rows.some((row) => typeof row[index] === "number") ? "right" : "left";
    return { key, label, align };
  });
  const normalizedRows = rows.map((row, idx) => {
    const out = { id: idx };
    row.forEach((value, index) => { out["c" + index] = value; });
    return out;
  });
  const wide = orientation || (headers.length > 6 ? "landscape" : "portrait");
  return {
    title,
    reportName: title,
    companyName,
    companyDetails,
    logoUrl,
    branchName,
    generatedBy,
    dateRange,
    filters,
    columns,
    rows: normalizedRows,
    totals,
    orientation: wide,
    generatedAt: Date.now(),
  };
}

export function ReportPreviewDialog({ report, onClose, onPrint, onDownloadPDF }) {
  if (!report) return null;
  return (
    <div className="scrim report-preview-scrim" onClick={onClose}>
      <div className="report-preview-modal" onClick={(e) => e.stopPropagation()}>
        <div className="report-preview-toolbar no-print">
          <div>
            <div className="sub" style={{ margin: 0 }}>Print Preview</div>
            <div className="title" style={{ fontSize: 19 }}>{report.title}</div>
          </div>
          <div className="expbtns">
            <button className="btn xs btn-primary" onClick={onPrint}>Print</button>
            <button className="btn xs btn-ghost" onClick={onDownloadPDF}>Save PDF</button>
            <button className="iconbtn" onClick={onClose}>x</button>
          </div>
        </div>
        <div className="report-preview-page">
          <PrintableReport report={report} />
        </div>
      </div>
    </div>
  );
}
